### ISSUE TITLE
Displaying dumps on binaries with dots in filename crashes the dump-browser

### ISSUE THREAD

**Issue by vakabus** [vakabus/gcopdd#10]
For example, when you dump reports from this JAR file without renaming it, dump-browser won't display anything at all, even when you wan't to look at a different report.
http://repo.scalabench.org/snapshots/org/scalabench/benchmarks/scala-benchmark-suite/0.1.0-SNAPSHOT/scala-benchmark-suite-0.1.0-20120216.103539-3.jar

My proposed solution would be to dump metadata into another file and do not keep them in the filename. That's calling for trouble What if I name my program `%20.jar` or `a+b.jar`, this might also cause other problems...

**Comment by rqu** [comment]
I can't reproduce this. The directories with dots in their names are ignored, but do not crash the browser.

There is actually a bug which causes the crash when there are *no other* dumps with a valid (dotless) names.

> My proposed solution would be to dump metadata into another file and do not keep them in the filename.

This would make the dump directory less manageable (what if you wanted to delete all dumps from a specific application?). The dump has got a name for the same reason your jarfile has got a name.

**Comment by rqu** [comment]
In 110c82c I fixed crashing on empty dump directory and added code substituting unsafe (non-alphanumeric) characters by underscores while generating the dump.
